import type { Metadata } from "next";

import "./globals.css";
import { Merriweather, Playfair_Display } from "next/font/google";
import Footer from "./components/Footer";





const merri = Merriweather({

  subsets: ['latin'],

  variable: '--font-merri',

  weight: "300"

});



const playfair = Playfair_Display({

  subsets: ['latin'],

  variable: '--font-play',

});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${merri.variable} ${playfair.variable} antialiased`}>
      
        {children}
   
      </body>
    </html>
  );
}
